// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FormDB_Property_Types from "./FormDB_Property_Types.res.js";
import * as FormDB_Property_Runner from "./FormDB_Property_Runner.res.js";
import * as FormDB_Property_Generators from "./FormDB_Property_Generators.res.js";

function prop_selectHasFrom(stmt) {
  if (stmt.includes("SELECT")) {
    return stmt.includes("FROM");
  } else {
    return false;
  }
}

function prop_insertHasInto(stmt) {
  if (stmt.includes("INSERT INTO")) {
    return stmt.includes("{");
  } else {
    return false;
  }
}

function prop_updateHasSetAndWhere(stmt) {
  if (stmt.includes("UPDATE") && stmt.includes("SET")) {
    return stmt.includes("WHERE");
  } else {
    return false;
  }
}

function prop_deleteHasWhere(stmt) {
  if (stmt.includes("DELETE FROM")) {
    return stmt.includes("WHERE");
  } else {
    return false;
  }
}

function prop_createHasCollection(stmt) {
  if (stmt.includes("CREATE")) {
    return stmt.includes("COLLECTION");
  } else {
    return false;
  }
}

function prop_dropHasCollection(stmt) {
  return stmt.includes("DROP COLLECTION");
}

function prop_explainWrapsQuery(stmt) {
  if (stmt.includes("EXPLAIN")) {
    return stmt.includes("SELECT");
  } else {
    return false;
  }
}

function prop_introspectHasTarget(stmt) {
  if (stmt.includes("INTROSPECT")) {
    if (stmt.includes("SCHEMA") || stmt.includes("CONSTRAINTS") || stmt.includes("COLLECTIONS")) {
      return true;
    } else {
      return stmt.includes("JOURNAL");
    }
  } else {
    return false;
  }
}

function prop_nonEmpty(stmt) {
  return stmt.length > 0;
}

function prop_validEnding(stmt) {
  var trimmed = stmt.trim();
  if (trimmed.length > 0) {
    return trimmed.length === stmt.length;
  } else {
    return false;
  }
}

function prop_validIdentifiers(stmt) {
  if (!stmt.includes("  ") && !stmt.includes(",,")) {
    return !stmt.startsWith(" ");
  } else {
    return false;
  }
}

function prop_balancedBraces(stmt) {
  var openCount = {
    contents: 0
  };
  var closeCount = {
    contents: 0
  };
  stmt.split("").forEach(function ($$char) {
        if ($$char === "{") {
          openCount.contents = openCount.contents + 1 | 0;
        }
        if ($$char === "}") {
          closeCount.contents = closeCount.contents + 1 | 0;
          return ;
        }
        
      });
  return openCount.contents === closeCount.contents;
}

function prop_balancedQuotes(stmt) {
  var count = {
    contents: 0
  };
  stmt.split("").forEach(function ($$char) {
        if ($$char === "\"") {
          count.contents = count.contents + 1 | 0;
          return ;
        }
        
      });
  return count.contents % 2 === 0;
}

function runFDQLProperties(configOpt) {
  var config = configOpt !== undefined ? configOpt : FormDB_Property_Types.defaultConfig;
  var tests = [
    [
      "SELECT statements have FROM clause",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "SELECT has FROM", FormDB_Property_Generators.selectStatement, (function (s) {
                        return s;
                      }), prop_selectHasFrom);
        })
    ],
    [
      "INSERT statements have INTO and document",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "INSERT has INTO", FormDB_Property_Generators.insertStatement, (function (s) {
                        return s;
                      }), prop_insertHasInto);
        })
    ],
    [
      "UPDATE statements have SET and WHERE",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "UPDATE has SET and WHERE", FormDB_Property_Generators.updateStatement, (function (s) {
                        return s;
                      }), prop_updateHasSetAndWhere);
        })
    ],
    [
      "DELETE statements have WHERE clause",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "DELETE has WHERE", FormDB_Property_Generators.deleteStatement, (function (s) {
                        return s;
                      }), prop_deleteHasWhere);
        })
    ],
    [
      "CREATE statements have COLLECTION",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "CREATE has COLLECTION", FormDB_Property_Generators.createStatement, (function (s) {
                        return s;
                      }), prop_createHasCollection);
        })
    ],
    [
      "DROP statements have COLLECTION",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "DROP has COLLECTION", FormDB_Property_Generators.dropStatement, (function (s) {
                        return s;
                      }), prop_dropHasCollection);
        })
    ],
    [
      "EXPLAIN statements wrap SELECT",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "EXPLAIN wraps query", FormDB_Property_Generators.explainStatement, (function (s) {
                        return s;
                      }), prop_explainWrapsQuery);
        })
    ],
    [
      "INTROSPECT statements have target",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "INTROSPECT has target", FormDB_Property_Generators.introspectStatement, (function (s) {
                        return s;
                      }), prop_introspectHasTarget);
        })
    ],
    [
      "All statements are non-empty",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "Non-empty", FormDB_Property_Generators.fdqlStatement, (function (s) {
                        return s;
                      }), prop_nonEmpty);
        })
    ],
    [
      "All statements have valid identifiers",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "Valid identifiers", FormDB_Property_Generators.fdqlStatement, (function (s) {
                        return s;
                      }), prop_validIdentifiers);
        })
    ],
    [
      "Braces are balanced",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "Balanced braces", FormDB_Property_Generators.fdqlStatement, (function (s) {
                        return s;
                      }), prop_balancedBraces);
        })
    ],
    [
      "Quotes are balanced",
      (function () {
          return FormDB_Property_Runner.runProperty(config, "Balanced quotes", FormDB_Property_Generators.fdqlStatement, (function (s) {
                        return s;
                      }), prop_balancedQuotes);
        })
    ]
  ];
  return FormDB_Property_Runner.runSuite(config, tests);
}

function $$default() {
  return runFDQLProperties(undefined);
}

export {
  prop_selectHasFrom ,
  prop_insertHasInto ,
  prop_updateHasSetAndWhere ,
  prop_deleteHasWhere ,
  prop_createHasCollection ,
  prop_dropHasCollection ,
  prop_explainWrapsQuery ,
  prop_introspectHasTarget ,
  prop_nonEmpty ,
  prop_validEnding ,
  prop_validIdentifiers ,
  prop_balancedBraces ,
  prop_balancedQuotes ,
  runFDQLProperties ,
  $$default as default,
}
/* No side effect */
